 inputSize = 257;
    outputSize = 257;
    numResponses = 257;
    
 
maxEpochs = 150;
miniBatchSize = 600;
featureDimension = 257;
numHiddenUnits = 257;
     options = trainingOptions('adam', ...
     'MaxEpochs',maxEpochs, ...
     'MiniBatchSize',miniBatchSize, ...
     'InitialLearnRate',0.2, ...
     'GradientThreshold',1, ...
     'Shuffle','never', ...
     'Plots','training-progress',...
     'Verbose',1);
 
  layers = [ ...
    sequenceInputLayer(inputSize)
    lstmLayer(outputSize,'OutputMode','sequence')
   
    fullyConnectedLayer(numResponses)
    regressionLayer];
    trainedNet = trainNetwork(wiener_all,real_wiener_all,layers,options) ;